// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyVy8K-xumUkiU7tkMifuMyalP06uuXpE',
    appId: '1:1034850681224:web:7ad5fc5e7c0dcedb41fa3d',
    messagingSenderId: '1034850681224',
    projectId: 'to-do-app-74838',
    authDomain: 'to-do-app-74838.firebaseapp.com',
    storageBucket: 'to-do-app-74838.firebasestorage.app',
    measurementId: 'G-KWT76M7WTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjsraSf0Ex4JFXpQOVBAD-TqBgw2tU-5k',
    appId: '1:1034850681224:android:181aaf5cb123ad9c41fa3d',
    messagingSenderId: '1034850681224',
    projectId: 'to-do-app-74838',
    storageBucket: 'to-do-app-74838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXhmmnwfoJUdUbIiDHy3IvKgAm-UOb_xE',
    appId: '1:1034850681224:ios:48f068431eb924bf41fa3d',
    messagingSenderId: '1034850681224',
    projectId: 'to-do-app-74838',
    storageBucket: 'to-do-app-74838.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXhmmnwfoJUdUbIiDHy3IvKgAm-UOb_xE',
    appId: '1:1034850681224:ios:48f068431eb924bf41fa3d',
    messagingSenderId: '1034850681224',
    projectId: 'to-do-app-74838',
    storageBucket: 'to-do-app-74838.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyVy8K-xumUkiU7tkMifuMyalP06uuXpE',
    appId: '1:1034850681224:web:c90578a634a63f1b41fa3d',
    messagingSenderId: '1034850681224',
    projectId: 'to-do-app-74838',
    authDomain: 'to-do-app-74838.firebaseapp.com',
    storageBucket: 'to-do-app-74838.firebasestorage.app',
    measurementId: 'G-YVPR2ZR6VE',
  );
}
